### ISSUE TITLE
QuadratureEncoder Get value 0

### ISSUE THREAD

**Issue by ahmedAlmasri** [martinohanlon/RobotPID#1]
Hello 

I'm trying to use QuadratureEncoder but always return a zero value 

My test code 

```
motors = Motors()
motors.stop()
motors.forword(90)
encoder_right_a = QuadratureEncoder(21, 20)
encoder_right_c = QuadratureEncoder(16, 5)

    
while True:
    
    print("en1 {} en2 {}".format(encoder_right_a.value, encoder_right_c.value))
    sleep(1)
```

**Comment by martinohanlon** [comment]
You haven't provided enough information for me to offer any advice. The questions which spring to mind are what encoder is it, what does the spec sheet say, is it connected correctly, what have you done to test it.

My memory, it was a very long time ago I wrote this, all the class does is treat the encoder like a switch. Perhaps try just test the encoder does actually output something.

**Comment by ghost** [comment]
Hi Martin, I have tried to run encoder.py. The motor was running but the encoder output  was always zero even with different SAMPLETIME. The oscilloscope showed a nice square wave around 1.7KHz. I am using quadrature encoder motor.  Motor specs are as follows:
Basic PPR: 7PPR
1.68-1.71 KHz@6V with oscilloscope
1680*60/7/100=144rpm
Will you be able to help me? Thanks! 
Thomas
![Untitled](https://user-images.githubusercontent.com/69731816/90320158-3ec8fd00-def3-11ea-9a54-76fc8030a822.png)
