### ISSUE TITLE
The encoder output is zero

### ISSUE THREAD

**Issue by ghost** [martinohanlon/RobotPID#2]
Hi Martin, I have tried to run encoder.py. The motor was running but the encoder output was always zero even with different SAMPLETIME. The oscilloscope showed a nice square wave around 1.7KHz. I am using quadrature encoder motor. Motor specs are as follows:
Basic PPR: 7PPR
1.68-1.71 KHz@6V with oscilloscope
1680*60/7/100=144rpm
Will you be able to help me? Thanks!
Thomas
![Untitled](https://user-images.githubusercontent.com/69731816/90320197-ac752900-def3-11ea-8de2-b37a524bd50b.png)

**Comment by martinohanlon** [comment]
Im sorry I dont have experience of this motor and without one to test I am not sure how I could help. I would recommend starting simple, getting the Pi the read each alternate signal and see if you can get it to count. Sorry.
